version: "2"

linters:
  default: standard
  enable:
    - cyclop
    - err113
    - gocognit
    - gocritic
    - gosec
    - musttag
    - recvcheck
    - revive
  settings:
    cyclop:
      max-complexity: 15
    gosec:
      excludes:
        - G204
    revive:
      rules:
        - name: exported
          disabled: true

run:
  timeout: 5m
  tests: false
