[tools]
go = "1.26"

[tasks.build]
description = "Build the database-mcp binary"
run = "go build -o bin/database-mcp"

[tasks.format]
description = "Format the code"
run = "go fmt ./..."

[tasks.lint]
description = "Run linter on the code"
run = "docker run -t --rm -v $PWD:/app -w /app golangci/golangci-lint:v2.9.0 golangci-lint run"

[tasks.test]
description = "Run tests"
run = "go test -v -race -cover -covermode=atomic ./..."
